# Generated by Django 2.0.2 on 2018-02-22 09:38

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='supporters/')),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'supporters',
            },
        ),
    ]
