# Generated by Django 2.0.2 on 2018-02-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporter',
            old_name='site_address',
            new_name='website',
        ),
    ]
