# Generated by Django 2.0.2 on 2018-02-21 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('google_plus', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Format: '+91999111999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='speakers/')),
            ],
            options={
                'verbose_name_plural': 'speakers',
            },
        ),
    ]
