# Generated by Django 2.0.2 on 2018-02-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='stackoverflow',
            field=models.URLField(blank=True),
        ),
    ]
