# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170723_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('google_plus', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supportfiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='email_id',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='ok_to_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Location'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Event'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Event'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='social_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.SocialLink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='social_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.SocialLink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporter',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Location'),
            preserve_default=False,
        ),
    ]
