# Generated by Django 2.0.2 on 2018-02-16 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField()),
                ('tw', models.URLField()),
                ('ln', models.URLField()),
                ('gp', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('desigination', models.CharField(choices=[('ORG', 'organiser'), ('CON', 'contributor')], default='CON', max_length=3)),
                ('contact_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('photo', models.ImageField(upload_to='organiser/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
