# Generated by Django 2.0.2 on 2018-02-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='gp',
            new_name='google_plus',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='ln',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='tw',
            new_name='twitter',
        ),
    ]
