# Generated by Django 2.0.2 on 2018-02-18 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_auto_20180217_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='contact_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Format: '+91999111999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='google_plus',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='organisers/'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
