# Generated by Django 2.0.2 on 2018-02-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_auto_20180218_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name_plural': 'testing'},
        ),
    ]
