# Generated by Django 2.0.2 on 2018-02-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_auto_20180222_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='stackoverflow',
            field=models.URLField(blank=True),
        ),
    ]
