# Generated by Django 2.0.2 on 2018-02-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_organizer_stackoverflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='desigination',
            new_name='role',
        ),
    ]
